name: Update stage branches

on:
  push:
    branches:
      - main

jobs:
  update-stage-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stage-a
      
      - name: Reset stage-a branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: chore/update-stage-a
          commit-message: "chore: update stage-a"
          title: "chore: update stage-a"
          labels: |
            stage-1
          base: stage-a

  update-stage-b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stage-b
      
      - name: Reset stage-b branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: chore/update-stage-b
          commit-message: "chore: update stage-b"
          title: "chore: update stage-b"
          labels: |
            stage-2
          base: stage-b
