name: Update stage branches

on:
  push:
    branches:
      - main

jobs:
  updateStage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: update stage-1
          title: Update stage-1
          branch: stage-1
          labels: |
            stage-1
            automated pr
          base: main

  updateStage2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: update stage-2
          title: Update stage-2
          branch: stage-2
          labels: |
            stage-2
            automated pr
          base: main
